let data=[
    {
        name:"Dhaka",
        district:[
            {name:"Dhaka"},
            {name:"Faridpur"},
            {name:"Gazipur"},
            {name:"Gopalganj"},
            {name:"Kishoreganj"},
            {name:"Madaripur"},
            {name:"Manikganj"},
            {name:"Narayanganj"},
            {name:"Narsingdi"},
            {name:"Rajbari"},
            {name:"Shariatpur"},
            {name:"Tangail"},
        ]
    },
    {
        name:"Sylhet",
        district:[
            {name:"Sylhet"},
            {name:"Habiganj"},
            {name:"Moulvibazar"},
            {name:"Sunamganj"},
        ]
    },
    {
        name:"Rangpur",
        district:[
            {name:"Rangpur"},
            {name:"Gaibandha"},
            {name:"Nilphamari"},
            {name:"Kurigram"},
            {name:"Lalmonirhat"},
            {name:"Dinajpur"},
            {name:"Thakurgaon"},
            {name:"Panchagarh"},
        ]
    },
    {
        name:"Rajshahi",
        district:[
            {name:"Rajshahi"},
            {name:"Joypurhat"},
            {name:"Naogaon"},
            {name:"Nawabganj"},
            {name:"Natore"},
            {name:"Pabna"},
            {name:"Sirajganj"},
        ]
    },
    {
        name:"Barishal",
        district:[
            {name:"Barisal"},
            {name:"Barguna"},
            {name:"Bhola"},
            {name:"Jhalokati"},
            {name:"Pirojpur"},
            {name:"Patuakhali"},
        ]
    },
    {
        name:"Chittagong",
        district:[
            {name:"Chittagong"},
            {name:"Cox's Bazar"},
            {name:"Rangamati"},
            {name:"Bandarban"},
            {name:"Khagrachhari"},
            {name:"Feni"},
            {name:"Lakshmipur"},
            {name:"Comilla"},
            {name:"Noakhali"},
            {name:"Brahmanbaria"},
            {name:"Chandpur"},
        ]
    },
    {
        name:"Mymensingh",
        district:[
            {name:"Mymensingh"},
            {name:"Tangail"},
            {name:"Jamalpur"},
            {name:"Kishoreganj"},
            {name:"Sherpur"},
            {name:"Netrokona"},
        ]
    },
    {
        name:"Khulna",
        district:[
            {name:"Khulna"},
            {name:"Bagherhat"},
            {name:"Sathkhira"},
            {name:"Jessore"},
            {name:"Magura"},
            {name:"Jhenaidah"},
            {name:"Narail"},
            {name:"Kushtia"},
            {name:"Chuadanga"},
            {name:"Meherpur"},
        ]
    },
]
export default data;